# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlip_sdk/nlip.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nlip_sdk/nlip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13nlip_sdk/nlip.proto\x12\x04nlip\"m\n\x0fNLIP_SubMessage\x12$\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x14.nlip.AllowedFormats\x12\x11\n\tsubformat\x18\x02 \x01(\t\x12\x16\n\x0ctext_content\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63ontent\"\x80\x01\n\x11NLIP_BasicMessage\x12\x0f\n\x07\x63ontrol\x18\x01 \x01(\x08\x12$\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x14.nlip.AllowedFormats\x12\x11\n\tsubformat\x18\x03 \x01(\t\x12\x16\n\x0ctext_content\x18\x04 \x01(\tH\x00\x42\t\n\x07\x63ontent\"\xa7\x01\n\x0cNLIP_Message\x12\x0f\n\x07\x63ontrol\x18\x01 \x01(\x08\x12$\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x14.nlip.AllowedFormats\x12\x11\n\tsubformat\x18\x03 \x01(\t\x12\x16\n\x0ctext_content\x18\x04 \x01(\tH\x00\x12*\n\x0bsubmessages\x18\x05 \x03(\x0b\x32\x15.nlip.NLIP_SubMessageB\t\n\x07\x63ontent*\\\n\x0e\x41llowedFormats\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05TOKEN\x10\x01\x12\x0e\n\nSTRUCTURED\x10\x02\x12\n\n\x06\x42INARY\x10\x03\x12\x0c\n\x08LOCATION\x10\x04\x12\x0b\n\x07GENERIC\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlip_sdk.nlip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLOWEDFORMATS']._serialized_start=441
  _globals['_ALLOWEDFORMATS']._serialized_end=533
  _globals['_NLIP_SUBMESSAGE']._serialized_start=29
  _globals['_NLIP_SUBMESSAGE']._serialized_end=138
  _globals['_NLIP_BASICMESSAGE']._serialized_start=141
  _globals['_NLIP_BASICMESSAGE']._serialized_end=269
  _globals['_NLIP_MESSAGE']._serialized_start=272
  _globals['_NLIP_MESSAGE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
